# Generated by Django 5.0.7 on 2024-07-22 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('pharmacist', 'Pharmacist'), ('patient', 'Patient'), ('admin', 'Admin')], default='patient', max_length=10),
        ),
    ]
