# Generated by Django 5.0.7 on 2024-07-20 22:27

import apps.appointments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='ФИО')),
                ('date_of_reservation', models.DateField(verbose_name='Дата записи')),
                ('time_of_reservation', models.TimeField(verbose_name='Время записи')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=50, verbose_name='Ваше имя')),
                ('your_email', models.EmailField(max_length=254, verbose_name='Ваш Email')),
                ('phone_number', models.CharField(max_length=15, validators=[apps.appointments.models.validate_phone_number], verbose_name='Номер телефона')),
                ('description', models.TextField(max_length=300, verbose_name='Описание')),
            ],
        ),
    ]
