# Generated by Django 5.0.7 on 2024-07-17 22:51

import apps.appointments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='description',
            field=models.TextField(max_length=300, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[apps.appointments.models.validate_phone_number], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='your_email',
            field=models.EmailField(max_length=254, verbose_name='Ваш Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='your_name',
            field=models.CharField(max_length=50, verbose_name='Ваше имя'),
        ),
    ]
