# Generated by Django 5.0.7 on 2024-07-17 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='time',
            new_name='working_hours',
        ),
    ]
